'https:' != location['protocol'] && (location['protocol'] = 'https:'), $(`${'<img style="width:100%;    margin-top: 0px;pointer-events:none;margin-bottom: 0px;" src="https://chatnsh.com/sico/z1eitbs0a510.png\x0D\x0A\x0D\x0A" >\x0D\x0A<div id="asim13"><a id="asim21" href="contact.html" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">اتصل بنا</a>\x0D\x0A<a id="asim21" href="rules.html" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">القوانين</a>\x0D\x0A<a id="asim21" href="Shortcut.html" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">اختصارات </a>\x0D\x0A<a id="asim21" href="https://blog.jfa-w.net/" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">المدونة</a>\x0D\x0A<a id="asim22" href="mobile.html" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">التطبيق</a>\x0D\x0A<a id="asim22" href="sub.html" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">الآشتراكات</a>\x0D\x0A<a id="asim22" href="https://www.abraj2015.com/" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">الأبراج</a>\x0D\x0A<a id="asim22" href="https://www.wadhefa.com/" target="_blank" type="button" style=" width: 24%; margin: 2px;" class="btn-as">وظائف</a></div></div><center>'}`)['insertBefore']('.nav-tabs'), $('.nav-tabs')['addClass']('fl')['css']('width', '100%'), $('.tc span[class="fa fl"]')['addClass']('fa-check');
var nopm = !0
    , nonot = !0;
$('.hand.nosel.fl.uzr.border')['css']({ margin: '1px 0', borderRadius: '0px' }), $(`${'<div><marquee direction="right" id="as43"scrollamount="3">اهلا وسهلا بكم\x0D\x0A\x0D\x0A <font class="a">   في شات عشقي للجوال </font>  نهني أنفسنا بحلول اليوم الوطني المجيد لأنه يحي بداخلنا شدة الانتماء إلى بلدنا الحبيب واعتزازً بوطننا.\x0D\x0A\x0D\x0Aأدامك الله يا وطني شامخًا رافعًا رأسك بأولادك.&nbsp;</marquee><div>'}`)['insertBefore']('div#tlogins .lonline.light.break'), $('.nav-tabs')['addClass']('fl')['css']('width', '100%');
var _0xb650 = ['maxlength', '500', 'attr', 'textarea#tbox.fl.corner.tbox.filw'];
$(_0xb650[3])[_0xb650[2]](_0xb650[0], _0xb650[1]);
var _0xb650 = ['maxlength', '12', 'attr', 'div#tlogins input'];
$(_0xb650[3])[_0xb650[2]](_0xb650[0], _0xb650[1]), $('div#tlogins button.btn.btn-primary')['click'](function () {
    var _0x5fb3x4 = setInterval(function () {
        var _0x5fb3x5 = $('.pmsgc')['length'];
        0 < _0x5fb3x5 ? ($(`${'<center><iframe width="390" height="140" src="" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe><center><center><div style=" width: 100%;height: auto!important; "  id="as" margin: 2px;" class="fa fa-heartbeat btn btn-danger" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; دأم عزك يأوطن ~> (اضغط هنا)&nbsp;</div><div class="collapse" id="collapseExample"><center><div class="well"><p lass="bg-primary"></i></p>وطني أرجو العذر إنْ خانتني حروفي وأرجو العفو إن أنقصت قدراً فما أنا إلّا عاشقٌ حاول أنْ يتغنى بحبِّ هذا الوطن. فكم أنا فخورٌ بانتماني إليك أيّها الوطن </p><jpg="" jpg=""><a href="#"><img src="https://i.top4top.io/p_1724d6a4u1.gif"style="width:99%;\x0D\x0Amargin-top: 30px;\x0D\x0A"></div><center>'}`)['appendTo']('div#chats'), clearInterval(_0x5fb3x4)) : console['log'](_0x5fb3x5)
    }, 1)
}), $(`${'<link rel="stylesheet" href="https://rawcdn.githack.com/omar-alhaded/chatnsh/d159c12593cc1e5962175f1f09c41c773824322b/alaeed-alo6ny.css"><style>.label-primary,.label-warning{background-image: -webkit-linear-gradient(45deg,rgba(255,255,255,.2) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.2) 50%,rgba(255,255,255,.2) 75%,transparent 75%,transparent)!important;border: 1px solid white!important;}.bgg.border.corner{right: 1px;}button.btn { border: 1px solid!important; }.tbox { margin-top: 2.4px!important; }\x0D\x0A</style>'}`)['insertBefore']('body');

function logout() { setTimeout(function () { close(0) }) }(document['getElementById']('tbox')['placeholder'] = '( اكتب رسالتك لشات عشقي )');
$(`${'<center><div><div width="99.5%" style="background-image:url();color: #ffffff;border-radius: 5px 5px 5px5px;border-bottom: 2px solid #ffffff;border-top: 2px solid#378a47;padding-bottom: 2px!important;" ><font style="background-color: #378a47;border-radius: 15px 15px 15px 15px;font-family: \'jazeera\',FontAwesome;padding: 2px 10px 2px 10px ;margin: 7px 10px 7px 10px;" >حيأكم الله بشات عشقي للجوال</font></div></div><center>'}`)['insertBefore']('#d2');
$('label.label.tc.border.cp.btn.label-danger.fl')['html']('<span class=\'fl fa fa-star\'></span> لوحة تحكم شأت عشقي ')

